
set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN B11 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]

set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports up]

set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDvals[0]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property PACKAGE_PIN T10 [get_ports {LEDvals[6]}]
set_property PACKAGE_PIN R10 [get_ports {LEDvals[5]}]
set_property PACKAGE_PIN K16 [get_ports {LEDvals[4]}]
set_property PACKAGE_PIN K13 [get_ports {LEDvals[3]}]
set_property PACKAGE_PIN P15 [get_ports {LEDvals[2]}]
set_property PACKAGE_PIN T11 [get_ports {LEDvals[1]}]
set_property PACKAGE_PIN L18 [get_ports {LEDvals[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports y3]
set_property IOSTANDARD LVCMOS33 [get_ports y2]
set_property PACKAGE_PIN M13 [get_ports y3]
set_property PACKAGE_PIN L16 [get_ports y2]
set_property IOSTANDARD LVCMOS33 [get_ports VSync]
set_property IOSTANDARD LVCMOS33 [get_ports up_fpga]
set_property PACKAGE_PIN B12 [get_ports VSync]
set_property PACKAGE_PIN M18 [get_ports up_fpga]
set_property PACKAGE_PIN V12 [get_ports up]
set_property PACKAGE_PIN D15 [get_ports ss]
set_property PACKAGE_PIN F15 [get_ports sclk]
set_property PACKAGE_PIN M17 [get_ports right_fpga]
set_property PACKAGE_PIN V15 [get_ports right]
set_property PACKAGE_PIN T15 [get_ports resty]
set_property IOSTANDARD LVCMOS33 [get_ports ss]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports right_fpga]
set_property PACKAGE_PIN U14 [get_ports restx]
set_property IOSTANDARD LVCMOS33 [get_ports restx]
set_property PACKAGE_PIN F14 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports left_fpga]
set_property PACKAGE_PIN E15 [get_ports miso]
set_property PACKAGE_PIN P17 [get_ports left_fpga]
set_property PACKAGE_PIN V14 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports down_fpga]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports choose]
set_property IOSTANDARD LVCMOS33 [get_ports a7]
set_property IOSTANDARD LVCMOS33 [get_ports a6]
set_property IOSTANDARD LVCMOS33 [get_ports a5]
set_property IOSTANDARD LVCMOS33 [get_ports a4]
set_property PACKAGE_PIN E3 [get_ports clock]
set_property PACKAGE_PIN R13 [get_ports choose]
set_property PACKAGE_PIN P18 [get_ports down_fpga]
set_property PACKAGE_PIN V11 [get_ports down]
set_property PACKAGE_PIN P14 [get_ports a7]
set_property PACKAGE_PIN T14 [get_ports a6]
set_property PACKAGE_PIN K2 [get_ports a5]
set_property PACKAGE_PIN U13 [get_ports a4]
set_property IOSTANDARD LVCMOS33 [get_ports resty]

set_property IOSTANDARD LVCMOS33 [get_ports sevenreset]
set_property PACKAGE_PIN U18 [get_ports sevenreset]


set_property IOSTANDARD LVCMOS33 [get_ports LED_out]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out2]
set_property PACKAGE_PIN K15 [get_ports LED_out]
set_property PACKAGE_PIN H17 [get_ports LED_out2]


set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CPU/DXLatch/regPC/d_flip_flop27/q_reg_1]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CPU/DXLatch/regPC/d_flip_flop2/q_reg_2]


set_property PACKAGE_PIN J15 [get_ports switch]
set_property IOSTANDARD LVCMOS33 [get_ports switch]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets CPU/DXLatch/regPC/d_flip_flop2/q_reg_3]
