module register_65bits(out, in, clk, input_enable, clr);

    input[64:0] in;
    input clk;
    input input_enable;
    input clr;
    output[64:0] out;

    dffe_ref_neg d_flip_flop0(out[0], in[0], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop1(out[1], in[1], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop2(out[2], in[2], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop3(out[3], in[3], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop4(out[4], in[4], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop5(out[5], in[5], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop6(out[6], in[6], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop7(out[7], in[7], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop8(out[8], in[8], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop9(out[9], in[9], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop10(out[10], in[10], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop11(out[11], in[11], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop12(out[12], in[12], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop13(out[13], in[13], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop14(out[14], in[14], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop15(out[15], in[15], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop16(out[16], in[16], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop17(out[17], in[17], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop18(out[18], in[18], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop19(out[19], in[19], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop20(out[20], in[20], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop21(out[21], in[21], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop22(out[22], in[22], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop23(out[23], in[23], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop24(out[24], in[24], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop25(out[25], in[25], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop26(out[26], in[26], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop27(out[27], in[27], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop28(out[28], in[28], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop29(out[29], in[29], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop30(out[30], in[30], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop31(out[31], in[31], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop32(out[32], in[32], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop33(out[33], in[33], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop34(out[34], in[34], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop35(out[35], in[35], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop36(out[36], in[36], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop37(out[37], in[37], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop38(out[38], in[38], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop39(out[39], in[39], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop40(out[40], in[40], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop41(out[41], in[41], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop42(out[42], in[42], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop43(out[43], in[43], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop44(out[44], in[44], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop45(out[45], in[45], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop46(out[46], in[46], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop47(out[47], in[47], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop48(out[48], in[48], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop49(out[49], in[49], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop50(out[50], in[50], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop51(out[51], in[51], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop52(out[52], in[52], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop53(out[53], in[53], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop54(out[54], in[54], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop55(out[55], in[55], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop56(out[56], in[56], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop57(out[57], in[57], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop58(out[58], in[58], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop59(out[59], in[59], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop60(out[60], in[60], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop61(out[61], in[61], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop62(out[62], in[62], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop63(out[63], in[63], clk, input_enable, clr);
    dffe_ref_neg d_flip_flop64(out[64], in[64], clk, input_enable, clr);

endmodule